/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/
#include <stddef.h>
#include <string.h>
/* FreeRTOS头文件 */
#include "FreeRTOS.h"
#include "task.h"
/* STemWIN头文件 */
#include "ScreenShot.h"
#include "MainTask.h"
#include "usart/bsp_debug_usart.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

/*********************************************************************
*
*       Types
*
**********************************************************************
*/


/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static char *_acbuffer = NULL;
static char _acBuffer[1024 * 4];

UINT    f_num;
extern FATFS   fs;								/* FatFs文件系统对象 */
extern FIL     file;							/* file objects */
extern FRESULT result; 
extern DIR     dir;

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/**
  * @brief 从存储器中读取数据
  * @note 无
  * @param 
  * @retval NumBytesRead：读到的字节数
  */
int _GetData(void * p, const U8 ** ppData, unsigned NumBytesReq, U32 Off)
{
	static int FileAddress = 0;
	UINT NumBytesRead;
	FIL *Picfile;
	
	Picfile = (FIL *)p;
	
	if(NumBytesReq > sizeof(_acBuffer))
	{NumBytesReq = sizeof(_acBuffer);}
	
	if(Off == 1) FileAddress = 0;
	else FileAddress = Off;
	result = f_lseek(Picfile, FileAddress);
	
	/* 进入临界段 */
	taskENTER_CRITICAL();
	result = f_read(Picfile, _acBuffer, NumBytesReq, &NumBytesRead);
	/* 退出临界段 */
	taskEXIT_CRITICAL();
	
	*ppData = (const U8 *)_acBuffer;
	
	return NumBytesRead;
}

/**
  * @brief 直接从存储器中绘制JPEG图片数据
  * @note 无
  * @param sFilename：需要加载的图片名
  * @retval 无
  */
static void ShowJPEGEx(const char *sFilename)
{
	/* 进入临界段 */
	taskENTER_CRITICAL();
	/* 打开图片 */
	result = f_open(&file, sFilename, FA_READ);
	if ((result != FR_OK))
	{
		printf("文件打开失败！\r\n");
		_acBuffer[0]='\0';
	}
	/* 退出临界段 */
	taskEXIT_CRITICAL();
	
	GUI_JPEG_DrawEx(_GetData, &file, 0, 0);
	
	/* 读取完毕关闭文件 */
	f_close(&file);
}

/**
  * @brief 加载JPEG图片到内存中并绘制
  * @note 无
  * @param sFilename：需要加载的图片名
  * @retval 无
  */
static void ShowJPEG(const char *sFilename)
{
	WM_HMEM hMem;
	
	/* 进入临界段 */
	taskENTER_CRITICAL();
	/* 打开图片 */
	result = f_open(&file, sFilename, FA_READ);
	if ((result != FR_OK))
	{
		printf("文件打开失败！\r\n");
		_acbuffer[0]='\0';
	}
	
	/* 申请一块动态内存空间 */
	hMem = GUI_ALLOC_AllocZero(file.fsize);
	/* 转换动态内存的句柄为指针 */
	_acbuffer = GUI_ALLOC_h2p(hMem);

	/* 读取图片数据到动态内存中 */
	result = f_read(&file, _acbuffer, file.fsize, &f_num);
	if(result != FR_OK)
	{
		printf("文件读取失败！\r\n");
	}
	/* 读取完毕关闭文件 */
	f_close(&file);
	/* 退出临界段 */
	taskEXIT_CRITICAL();
	
	GUI_JPEG_Draw(_acbuffer, file.fsize, 0, 0);
	
	/* 释放内存 */
	GUI_ALLOC_Free(hMem);
}

/**
  * @brief 加载JPEG图片数据到内存设备
  * @note 无
  * @param sFilename：需要加载的图片名
  * @retval 无
  */
static WM_HMEM LoadJPEG_UsingMEMDEV(const char *sFilename)
{
	WM_HMEM hMem;
	GUI_MEMDEV_Handle hJPEG;
	GUI_JPEG_INFO Jpeginfo;
	
	/* 进入临界段 */
	taskENTER_CRITICAL();
	/* 打开图片 */
	result = f_open(&file, sFilename, FA_OPEN_EXISTING | FA_READ);
	if ((result != FR_OK))
	{
		printf("文件打开失败！\r\n");
		_acbuffer[0]='\0';
	}
	
	/* 申请一块动态内存空间 */
	hMem = GUI_ALLOC_AllocZero(file.fsize);
	/* 转换动态内存的句柄为指针 */
	_acbuffer = GUI_ALLOC_h2p(hMem);

	/* 读取图片数据到动态内存中 */
	result = f_read(&file, _acbuffer, file.fsize, &f_num);
	if(result != FR_OK)
	{
		printf("文件读取失败！\r\n");
	}
	/* 读取完毕关闭文件 */
	f_close(&file);
	/* 退出临界段 */
	taskEXIT_CRITICAL();
	
	GUI_JPEG_GetInfo(_acbuffer, file.fsize, &Jpeginfo);
	
	/* 创建内存设备 */
	hJPEG = GUI_MEMDEV_CreateEx(0, 0,                /* 起始坐标 */
														 Jpeginfo.XSize,      /* x方向尺寸 */
														 Jpeginfo.YSize,      /* y方向尺寸 */
														 GUI_MEMDEV_HASTRANS);/* 带透明度的内存设备 */
	/* 选择内存设备 */
	GUI_MEMDEV_Select(hJPEG);
	/* 绘制JPEG到内存设备中 */
	GUI_JPEG_Draw(_acbuffer, file.fsize, 0, 0);
	/* 选择内存设备，0表示选中LCD */
	GUI_MEMDEV_Select(0);
	/* 释放内存 */
	GUI_ALLOC_Free(hMem);
	
	return hJPEG;
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/**
  * @brief GUI主任务
  * @note 无
  * @param 无
  * @retval 无
  */
void MainTask(void)
{
  int i = 0;
  uint16_t t0 = 0;
  uint16_t t1 = 0;
  
	GUI_MEMDEV_Handle hJPEG;
	
	GUI_SetFont(GUI_FONT_24B_ASCII);
	GUI_SetTextMode(GUI_TM_TRANS);
  GUI_SetColor(GUI_WHITE);
	
  /* 加载JPEG图片数据到内存设备 */
	hJPEG = LoadJPEG_UsingMEMDEV("0:/image/FORD_GT.jpg");
	
	while (1)
	{
    i++;
    switch(i)
    {
			case 1:
				t0 = GUI_GetTime();
				/* 直接从外部存储器绘制JPEG图片 */
				ShowJPEGEx("0:/image/FORD_GT.jpg");
				t1 = GUI_GetTime();
        GUI_DispStringHCenterAt("GUI_JPEG_DrawEx()", 400, 0);
        printf("\r\n直接从外部存储器绘制JPEG：%dms\r\n",t1 - t0);
				break;
			case 2:
				t0 = GUI_GetTime();
				/* 加载JPEG图片到内存中并绘制 */
				ShowJPEG("0:/image/FORD_GT.jpg");
				t1 = GUI_GetTime();
        GUI_DispStringHCenterAt("GUI_JPEG_Draw()", 400, 0);
        printf("加载JPEG到内存中并绘制：%dms\r\n",t1 - t0);
				break;
      case 3:
        t0 = GUI_GetTime();
        /* 从内存设备写入LCD */
        GUI_MEMDEV_CopyToLCDAt(hJPEG, 0, 0);
        t1 = GUI_GetTime();
        GUI_DispStringHCenterAt("USE MEMDEV", 400, 0);
        printf("使用内存设备显示JPEG：%dms\r\n",t1 - t0);
        break;
      default:
        i = 0;
        break;
    }
		GUI_Delay(2000);
		GUI_Clear();
	}
}

/*************************** End of file ****************************/
