/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "RadioDLG.h"
#include "./usart/bsp_debug_usart.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_RADIO_0      (GUI_ID_USER + 0x01)

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 480, 854, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio0", ID_RADIO_0, 60, 40, 120, 400, 0, 0x3207, 0 },
};

static const GUI_COLOR aColor[] = {GUI_WHITE, GUI_RED, GUI_GREEN,
                                   GUI_BLUE, GUI_CYAN, GUI_MAGENTA,
                                   GUI_ORANGE};
              
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/**
  * @brief 对话框回调函数
  * @note 无
  * @param pMsg：消息指针
  * @retval 无
  */
int value = 0;
static void _cbDialog(WM_MESSAGE* pMsg) {
	WM_HWIN hItem;
	int     NCode;
	int     Id;
  
	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		/* 初始化Framewin控件 */
		hItem = pMsg->hWin;
		FRAMEWIN_SetTitleHeight(hItem, 32);
		FRAMEWIN_SetText(hItem, "STemWIN@EmbedFire STM32F407");
		FRAMEWIN_SetFont(hItem, GUI_FONT_32_ASCII);
		/* 初始化Radio控件0 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
		RADIO_SetFont(hItem, GUI_FONT_24_ASCII);
		RADIO_SetText(hItem, "WHITE",   0);
		RADIO_SetText(hItem, "RED",     1);
		RADIO_SetText(hItem, "GREEN",   2);
		RADIO_SetText(hItem, "BLUE",    3);
    RADIO_SetText(hItem, "CYAN",    4);
    RADIO_SetText(hItem, "MAGENTA", 5);
    RADIO_SetText(hItem, "ORANGE",  6);
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case ID_RADIO_0: // Notifications sent by 'Radio0'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
				value = RADIO_GetValue(hItem);
        WM_InvalidateWindow(pMsg->hWin);
				break;
			}
			break;
		}
		break;
  case WM_PAINT:
    GUI_SetBkColor(aColor[value]);
    GUI_Clear();
    break;
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
 /**
  * @brief 以对话框方式间接创建控件
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

/**
  * @brief GUI主任务
  * @note 无
  * @param 无
  * @retval 无
  */
void MainTask(void)
{
	CreateFramewin();

	while(1)
	{
		GUI_Delay(10);
	}
}

/*************************** End of file ****************************/
