/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "TextDLG.h"
#include <stdio.h>

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_TEXT_0   (GUI_ID_USER + 0x01)
#define ID_TEXT_1   (GUI_ID_USER + 0x02)
#define ID_TEXT_2   (GUI_ID_USER + 0x03)
#define ID_TEXT_3   (GUI_ID_USER + 0x04)
#define ID_TEXT_4   (GUI_ID_USER + 0x05)

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "", ID_FRAMEWIN_0, 0, 0, 480, 854, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text0", ID_TEXT_0, 30, 25, 460, 50, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text1", ID_TEXT_1, 30, 120, 100, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text2", ID_TEXT_2, 30, 165, 100, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text3", ID_TEXT_3, 30, 210, 100, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text4", ID_TEXT_4, 30, 250, 250, 130, 0, 0x64, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static void _cbDialog(WM_MESSAGE* pMsg) {
	WM_HWIN hItem;
	
	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		/* 初始化Text0 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetFont(hItem, GUI_FONT_COMIC24B_ASCII);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		TEXT_SetText(hItem, "STemWIN@EmbedFire STM32F407");
		/* 初始化Text1 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetFont(hItem, GUI_FONT_8X16X1X2);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		TEXT_SetText(hItem, "Text");
		/* 初始化Text2 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetFont(hItem, GUI_FONT_8X16X2X2);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		TEXT_SetText(hItem, "Text");
		/* 初始化Text3 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetFont(hItem, GUI_FONT_8X16X3X3);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		TEXT_SetText(hItem, "Text");
		/* 初始化Text4 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
		TEXT_SetFont(hItem, GUI_FONT_D48X64);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetDec(hItem, 0, 5, 0, 0, 0);
		break;
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
 /**
  * @brief 以对话框方式间接创建控件
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
	WM_HWIN hWin;
	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

/**
  * @brief GUI主任务
  * @note 无
  * @param 无
  * @retval 无
  */
void MainTask(void)
{
	WM_HWIN hWin;
  WM_HWIN hItem;
  U32 temp = 0;
  
  /* 创建对话框 */
	hWin = CreateFramewin();	
  /* 获取子控件句柄 */
  hItem = WM_GetDialogItem(hWin, ID_TEXT_4);
	while(1)
	{
    /* 使用文本控件显示数值 */
		TEXT_SetDec(hItem, temp, 5, 0, 0, 0);
		temp++;
		if(temp > 99999)
		{
			temp = 0;
		}
    /* 延时100ms */
		GUI_Delay(20);
	}
}
/*************************** End of file ****************************/
