/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "EditDLG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_EDIT_0     (GUI_ID_USER + 0x01)
#define ID_BUTTON_0   (GUI_ID_USER + 0x02)
#define ID_BUTTON_1   (GUI_ID_USER + 0x03)

#define WM_APP_SHOW_TEXT (WM_USER + 0)/* 自定义消息类型 */
#define WM_HIDE_DLG      (WM_USER + 1)

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 400, 192, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit0", ID_EDIT_0, 120, 20, 150, 50, 0, 0x64, 0 },
	{ BUTTON_CreateIndirect, "OK", ID_BUTTON_0, 30, 100, 110, 40, 0, 0x64, 0 },
	{ BUTTON_CreateIndirect, "Cancel", ID_BUTTON_1, 250, 100, 110, 40, 0, 0x64, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/**
  * @brief _cbBk
  * @note 背景桌面回调函数
  * @param pMsg：消息指针
  * @retval 无
  */
static void _cbBk(WM_MESSAGE * pMsg)
{
	static WM_HWIN hItem;
	static WM_HWIN hEdit;
  static U8      ShowText;
	char aBuffer[40] = {0};
	
  switch (pMsg->MsgId) {
  case WM_PAINT:
    GUI_SetBkColor(GUI_LIGHTGRAY);
    GUI_Clear();
    GUI_SetFont(&GUI_Font24_ASCII);
    if (ShowText) {
			hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
      GUI_DispStringHCenterAt("The string you have modified is:", 400, 228);
      EDIT_GetText(hEdit, aBuffer, 40);
      GUI_DispStringHCenterAt(aBuffer, 400, 284);
			} else {
      GUI_DispStringHCenterAt("Use keyboard to modify string...", 400, 228);
    }
    break;
	case WM_APP_SHOW_TEXT:/* 隐藏窗口 */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_FRAMEWIN_0);
    WM_HideWindow(hItem);
    ShowText = 1;
    WM_InvalidateWindow(WM_HBKWIN);
    WM_CreateTimer(WM_HBKWIN, 0, 3000, 0);
    break;
  case WM_HIDE_DLG:/* 隐藏窗口 */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_FRAMEWIN_0);
    WM_HideWindow(hItem);
    WM_InvalidateWindow(WM_HBKWIN);
    WM_CreateTimer(WM_HBKWIN, 0, 3000, 0);
    break;
  case WM_TIMER:/* 到时间显示窗口 */
    ShowText = 0;
    WM_InvalidateWindow(WM_HBKWIN);
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_FRAMEWIN_0);
    WM_ShowWindow(hItem);
    break;
  default:
    WM_DefaultProc(pMsg);
  }
}

/**
  * @brief 对话框回调函数
  * @note 无
  * @param pMsg：消息指针
  * @retval 无
  */
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	WM_MESSAGE Msg;

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    /* Framewin初始化 */
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_20_ASCII);
    FRAMEWIN_SetTitleHeight(hItem, 20);
    FRAMEWIN_SetText(hItem, "STemWIN@EmbeddedFire STM32F429");
    /* Edit0初始化 */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "TEXT");
    EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	  EDIT_EnableBlink(hItem, 500, 1);
	  /* OK按钮初始化 */
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	  BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
	  /* cancel按钮初始化 */
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	  BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit0'
      switch(NCode) {
				case WM_NOTIFICATION_CLICKED:
					break;
				case WM_NOTIFICATION_RELEASED:
					break;
				case WM_NOTIFICATION_VALUE_CHANGED:
					break;
      }
      break;
		case ID_BUTTON_0: // Notifications sent by 'OK'
			switch(NCode) {
				case WM_NOTIFICATION_CLICKED:
					break;
				case WM_NOTIFICATION_RELEASED:
					Msg.MsgId=WM_APP_SHOW_TEXT;
					Msg.hWinSrc=pMsg->hWin;
					WM_SendMessage(WM_HBKWIN,&Msg);
					break;
				case WM_NOTIFICATION_VALUE_CHANGED:
					break;
			}
		  break;
		case ID_BUTTON_1: // Notifications sent by 'Cancel'
			switch(NCode) {
				case WM_NOTIFICATION_CLICKED:
					break;
				case WM_NOTIFICATION_RELEASED:
					Msg.MsgId=WM_HIDE_DLG;
					Msg.hWinSrc=pMsg->hWin;
					WM_SendMessage(WM_HBKWIN,&Msg);
					break;
				case WM_NOTIFICATION_VALUE_CHANGED:
					break;
			}
		  break;
	  }
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
 /**
  * @brief 以对话框方式间接创建控件
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

/**
  * @brief GUI主任务
  * @note 无
  * @param 无
  * @retval 无
  */
void MainTask(void)
{
	/* 设置背景色 */
	GUI_SetBkColor(GUI_GRAY_3F);
	GUI_Clear();
	/* 重定向背景窗口的回调函数 */
	WM_SetCallback(WM_HBKWIN, _cbBk);
	/* 间接创建窗口 */
	CreateFramewin();

	while (1)
	{
		GUI_Delay(20);
	}
}

/*************************** End of file ****************************/
