/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "MainTask.h"
#include "GUIFont_Create.h"
/* FreeRTOS头文件 */
#include "FreeRTOS.h"
#include "task.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
extern const char text[];

/*********************************************************************
*
*       _aDialogCreate
*/

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/**
  * @brief GUI主任务
  * @note 无
  * @param 无
  * @retval 无
  */
void MainTask(void)
{
  /* 启用UTF-8编码 */
  GUI_UC_SetEncodeUTF8();
  /* 创建字体 */
  Create_TTF_Font();
  
	/* 设置背景颜色 */
	GUI_SetBkColor(GUI_WHITE);
	GUI_Clear();
  
  /* 设置字体模式和颜色 */
  GUI_SetTextMode(GUI_TM_TRANS);
  GUI_SetColor(GUI_BLACK);

  /* 显示中文 */
  GUI_SetFont(&FONT_TTF_24);
  GUI_DispString(text);
  GUI_DispNextLine();
  GUI_SetFont(&FONT_TTF_48);
  GUI_DispString(text);
  GUI_DispNextLine();
  GUI_SetFont(&FONT_TTF_72);
  GUI_DispString(text);
  GUI_DispNextLine();
  GUI_SetFont(&FONT_TTF_96);
  GUI_DispString(text);
  GUI_DispNextLine();
  GUI_SetFont(&FONT_TTF_120);
  GUI_DispString(text);
  
	while(1)
	{
		GUI_Delay(1000);
	}
}

/*************************** End of file ****************************/
