/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "RadioDLG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_RADIO_0      (GUI_ID_USER + 0x01)
#define ID_RADIO_1      (GUI_ID_USER + 0x02)
#define ID_TEXT_0       (GUI_ID_USER + 0x03)

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
extern GUI_CONST_STORAGE GUI_BITMAP bmRadioUnsel;
extern GUI_CONST_STORAGE GUI_BITMAP bmRadioSel;

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
  { RADIO_CreateIndirect, "Radio0", ID_RADIO_0, 60, 60, 120, 200, 0, 0x3204, 0 },
	{ RADIO_CreateIndirect, "Radio1", ID_RADIO_1, 200, 60, 120, 200, 0, 0x3202, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_0, 440, 140, 170, 40, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/**
  * @brief 对话框回调函数
  * @note 无
  * @param pMsg：消息指针
  * @retval 无
  */
static void _cbDialog(WM_MESSAGE* pMsg) {
	WM_HWIN hItem;
	int     NCode;
	int     Id;
	int     value;
	char    radiobuf[8];
	
	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		/* 初始化Framewin控件 */
		hItem = pMsg->hWin;
		FRAMEWIN_SetTitleHeight(hItem, 32);
		FRAMEWIN_SetText(hItem, "STemWIN@EmbeddedFire STM32F429");
		FRAMEWIN_SetFont(hItem, GUI_FONT_32_ASCII);
		/* 初始化Radio控件0 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
		RADIO_SetFont(hItem, GUI_FONT_24_ASCII);
		RADIO_SetText(hItem, "Option0", 0);
		RADIO_SetText(hItem, "Option1", 1);
		RADIO_SetText(hItem, "Option2", 2);
		RADIO_SetText(hItem, "Option3", 3);
		/* 初始化Radio控件1 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_1);
		RADIO_SetSkinClassic(hItem);
		RADIO_SetImage(hItem, &bmRadioUnsel, RADIO_BI_ACTIV);
		RADIO_SetImage(hItem, &bmRadioSel, RADIO_BI_CHECK);
		RADIO_SetFont(hItem, GUI_FONT_24_ASCII);
		RADIO_SetText(hItem, "Option5", 0);
		RADIO_SetText(hItem, "Option6", 1);
		/* 初始化Text控件 */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case ID_RADIO_0: // Notifications sent by 'Radio0'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
				value = RADIO_GetValue(hItem);
				RADIO_GetText(hItem, value, radiobuf, sizeof(radiobuf));
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
				switch(value)
				{
					case 0:
						TEXT_SetText(hItem, radiobuf);
						break;
					case 1:
						TEXT_SetText(hItem, radiobuf);
						break;
					case 2:
						TEXT_SetText(hItem, radiobuf);
						break;
					case 3:
						TEXT_SetText(hItem, radiobuf);
						break;
					default:
						break;
				}
				break;
			}
			break;
		case ID_RADIO_1: // Notifications sent by 'Radio1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_1);
				value = RADIO_GetValue(hItem);
				RADIO_GetText(hItem, value, radiobuf, sizeof(radiobuf));
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
				switch(value)
				{
					case 0:
						TEXT_SetText(hItem, radiobuf);
						break;
					case 1:
						TEXT_SetText(hItem, radiobuf);
						break;
					default:
						break;
				}
				break;
			}
			break;
		}
		break;
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
 /**
  * @brief 以对话框方式间接创建控件
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

/**
  * @brief GUI主任务
  * @note 无
  * @param 无
  * @retval 无
  */
void MainTask(void)
{
	CreateFramewin();

	while(1)
	{
		GUI_Delay(10);
	}
}

/*************************** End of file ****************************/
