/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "ListboxDLG.h"

#include <stdio.h>

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x02)
#define ID_LISTBOX_0   (GUI_ID_USER + 0x03)
#define ID_BUTTON_0   (GUI_ID_USER + 0x04)
#define ID_BUTTON_1   (GUI_ID_USER + 0x05)
#define ID_TEXT_0   (GUI_ID_USER + 0x06)

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 140, 50, 170, 225, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button0", ID_BUTTON_0, 400, 50, 130, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button1", ID_BUTTON_1, 400, 215, 130, 60, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, " ", ID_TEXT_0, 400, 135, 130, 60, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/**
  * @brief 对话框回调函数
  * @note 无
  * @param pMsg：消息指针
  * @retval 无
  */
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	int     item_num;
	static char ItemNumBuf[10], ItemBuf[10];

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    /* 初始化Framewin控件 */
    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem, "STemWIN@EmbeddedFire STM32F429");
    FRAMEWIN_SetFont(hItem, GUI_FONT_32_ASCII);
    FRAMEWIN_SetTitleHeight(hItem, 32);
	
    /* 初始化Listbox控件 */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "Item0");
    LISTBOX_AddString(hItem, "Item1");
    LISTBOX_AddString(hItem, "Item2");
    LISTBOX_AddString(hItem, "Item3");
    LISTBOX_AddString(hItem, "Item4");
	  /* 设置Listbox内容字体格式 */
    LISTBOX_SetFont(hItem, GUI_FONT_COMIC24B_ASCII);
	  /* 开启自动使用水平和垂直滚动条 */
		LISTBOX_SetAutoScrollH(hItem, 1);
		LISTBOX_SetAutoScrollV(hItem, 1);
		/* 设置滚动条宽度 */
		LISTBOX_SetScrollbarWidth(hItem, 20);
		
		/* 初始化Button0 */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Add new item");
    BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
    /* 初始化Button1 */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "Delete item");
    BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
		
		/* 初始化Text控件 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_COMIC24B_ASCII);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);/* 获取句柄 */
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				item_num = LISTBOX_GetSel(hItem);/* 获取以被选中item的索引号 */
				LISTBOX_GetItemText(hItem, item_num, ItemBuf, 10);/* 获取索引号对应的item文本 */
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);/* 获取句柄 */
				TEXT_SetText(hItem, ItemBuf);/* 显示item文本 */
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        break;
      }
      break;
		case ID_BUTTON_0: // Notifications sent by 'Button0'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				item_num = LISTBOX_GetNumItems(hItem);/* 获取item总数 */
				item_num = (item_num - 1) + 1;/* 计算下一个item文本的序号 */
			  sprintf(ItemNumBuf, "Item%d", item_num);
			  LISTBOX_AddString(hItem, ItemNumBuf);/* 添加新的item */
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button1'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				item_num = LISTBOX_GetNumItems(hItem);/* 获取item总数 */
			  if(item_num == 1)/* 保留一个item */
					break;
				else {
					item_num = item_num - 1;
					LISTBOX_DeleteItem(hItem, item_num);/* 删除最后一个item */
				}
        break;
      }
      break;
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
 /**
  * @brief 资源表方式间接创建对话框
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

/**
  * @brief GUI主任务
  * @note 无
  * @param 无
  * @retval 无
  */
void MainTask(void)
{
	CreateFramewin();
	
	while(1)
	{
		GUI_Delay(10);
	}
}
/*************************** End of file ****************************/
